package io.springbootlab.springbootdynamoDb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@DynamoDBTable(tableName = "Product")
public class Product {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String productId;//partition key-Maps a class property to the partition key of a global secondary index
    @DynamoDBRangeKey
    private String productCategory;//sort-key-Maps a class property to the sort key of the table.
    @DynamoDBAttribute
    private String productName;
    @DynamoDBAttribute
    private Integer price;
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    @DynamoDBAttribute
    private Boolean isAvl;
    @DynamoDBAttribute
    private String expireDate;
    @DynamoDBAttribute
    private ProductOrigin productOrigin;
}
